### ISSUE TITLE
Website is not reachable

### ISSUE THREAD

**Issue by xeladu** [Key2img/Source#1]
Hey,

I love your service, it's perfect to visualize keyboard shortcuts for my blog. Currently, the website is running into a timeout if I try to reach it. I don't know how long that has been going on but I thought you might want to know so that you can take action if necessary.

Again, good job here!

**Comment by pegvin** [comment]
Hi there, the free domain i had was for 12 months and has expired, i would like you to try this url instead: https://key2img.github.io/
